version: '3.3'

services:
  frontend:
    image: './frontend'
    stdin_open: true
    ports:
      - '3000:3000'
  server:
    build: './server'
    ports:
      - '5000:5000'
    depends_on:
      - db
    command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'index.js']
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - APP_DB_USER=alteos
      - APP_DB_PASS=123456
      - APP_DB_NAME=alteos
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'alteos', '-U', 'alteos']
      timeout: 45s
      interval: 10s
      retries: 10
volumes:
  data:
