version: '3.3'

services:
  server:
    build: .
    ports:
      - '5000:5000'
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'alteos'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
