#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE data (
      _id VARCHAR(50) PRIMARY KEY,
      age INTEGER NOT NULL,
      eye_color VARCHAR ( 50 ) NOT NULL,
      name VARCHAR ( 100 ) NOT NULL,
      gender VARCHAR ( 50 ) NOT NULL,
      company VARCHAR ( 50 ) NOT NULL,
      email VARCHAR ( 255 ) UNIQUE NOT NULL,
      phone VARCHAR ( 50 ) UNIQUE NOT NULL,
      address VARCHAR ( 255 ) UNIQUE NOT NULL
	);
  COMMIT;
EOSQL